<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HW2247" name="com.mobile.automation.scripts.QuoteError_Android" tests="30" failures="3" timestamp="30 Mar 2018 13:03:41 GMT" time="3212.979" errors="0">
  <testcase name="QuoteErrorResult_Android" time="2.300" classname="com.mobile.automation.scripts.QuoteError_Android">
    <failure type="java.lang.AssertionError" message="Test Case Failed because - Failed to complete QuoteErrorResult">
      <![CDATA[java.lang.AssertionError: Test Case Failed because - Failed to complete QuoteErrorResult
	at org.testng.Assert.fail(Assert.java:93)
	at com.mobile.automation.scripts.QuoteError_Android.TestCaseStatus(QuoteError_Android.java:40)
	at com.mobile.automation.scripts.QuoteError_Android.QuoteErrorResult_Android(QuoteError_Android.java:100)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- QuoteErrorResult_Android -->
  <testcase name="QuoteErrorResult_Android" time="110.006" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="109.095" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="106.860" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="103.531" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="104.457" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="111.749" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="98.228" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="103.745" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="110.370" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="105.169" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="103.878" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="110.995" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="110.836" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="438.124" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="104.759" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="110.952" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="103.968" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="99.539" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="107.809" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="103.169" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="104.733" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="101.088" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="118.307" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="107.169" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="109.173" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="0.288" classname="com.mobile.automation.scripts.QuoteError_Android">
    <failure type="java.lang.AssertionError" message="Test Case Failed because - Failed to complete QuoteErrorResult">
      <![CDATA[java.lang.AssertionError: Test Case Failed because - Failed to complete QuoteErrorResult
	at org.testng.Assert.fail(Assert.java:93)
	at com.mobile.automation.scripts.QuoteError_Android.TestCaseStatus(QuoteError_Android.java:40)
	at com.mobile.automation.scripts.QuoteError_Android.QuoteErrorResult_Android(QuoteError_Android.java:100)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- QuoteErrorResult_Android -->
  <testcase name="QuoteErrorResult_Android" time="103.738" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="108.898" classname="com.mobile.automation.scripts.QuoteError_Android"/>
  <testcase name="QuoteErrorResult_Android" time="0.046" classname="com.mobile.automation.scripts.QuoteError_Android">
    <failure type="java.lang.AssertionError" message="Test Case Failed because - Failed to complete QuoteErrorResult">
      <![CDATA[java.lang.AssertionError: Test Case Failed because - Failed to complete QuoteErrorResult
	at org.testng.Assert.fail(Assert.java:93)
	at com.mobile.automation.scripts.QuoteError_Android.TestCaseStatus(QuoteError_Android.java:40)
	at com.mobile.automation.scripts.QuoteError_Android.QuoteErrorResult_Android(QuoteError_Android.java:100)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- QuoteErrorResult_Android -->
</testsuite> <!-- com.mobile.automation.scripts.QuoteError_Android -->
